alter session set container = XEPDB1;

CREATE SEQUENCE ADM_OWNER.APP_ID
    INCREMENT BY 1
    START WITH 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE SEQUENCE ADM_OWNER.APP_ENV_ID
    INCREMENT BY 1
    START WITH 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE SEQUENCE ADM_OWNER.DEPLOY_JOB_ID
    INCREMENT BY 1
    START WITH 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE TABLE ADM_OWNER.SETTING
(
    KEY                VARCHAR2(128 CHAR)  NOT NULL,
    VALUE              VARCHAR2(4000 BYTE) NOT NULL,
    TYPE               VARCHAR2(32 CHAR) DEFAULT 'STRING' NOT NULL,
    DESCRIPTION        VARCHAR2(2048 CHAR) NOT NULL,
    TAG                VARCHAR2(32 CHAR) DEFAULT 'OTHER' NOT NULL,
    WEIGHT             INTEGER DEFAULT 0 NOT NULL,
    CHANGE_ACTION_JNDI VARCHAR2(128 CHAR) NULL ,
    CONSTRAINT SETTING_PK PRIMARY KEY (KEY),
    CONSTRAINT SETTING_CK1 CHECK (TYPE IN ('STRING', 'BOOLEAN', 'CSV')),
    CONSTRAINT SETTING_CK2 CHECK ((VALUE in ('Y', 'N') AND TYPE = 'BOOLEAN') OR TYPE <> 'BOOLEAN')
);

CREATE TABLE ADM_OWNER.APP
(
    APP_ID              INTEGER NOT NULL ,
    NAME                VARCHAR2(128 CHAR) NOT NULL ,
    DOC_URL             VARCHAR2(512 CHAR) NULL ,
    CONSTRAINT APP_PK PRIMARY KEY (APP_ID) ,
    CONSTRAINT APP_AK1 UNIQUE (NAME)
);

CREATE TABLE ADM_OWNER.APP_ENV
(
    APP_ENV_ID           INTEGER NOT NULL ,
    APP_ID               INTEGER NOT NULL ,
    NAME                 VARCHAR2(128 CHAR) NOT NULL ,
    REQUEST_SERVICE_USERNAME VARCHAR2(128 CHAR) NOT NULL ,
    RUN_SERVICE_USERNAME VARCHAR2(128 CHAR) NOT NULL ,
    HOSTNAME             VARCHAR2(128 CHAR) NOT NULL ,
    PORT                 INTEGER NOT NULL ,
    DEPLOY_COMMAND       VARCHAR2(256 CHAR) NOT NULL ,
    CONSTRAINT APP_ENV_PK PRIMARY KEY (APP_ENV_ID) ,
    CONSTRAINT APP_ENV_FK1 FOREIGN KEY (APP_ID) REFERENCES ADM_OWNER.APP (APP_ID) ON DELETE CASCADE ,
    CONSTRAINT APP_ENV_AK1 UNIQUE (APP_ID,NAME)
);

CREATE TABLE ADM_OWNER.DEPLOY_JOB
(
    DEPLOY_JOB_ID INTEGER NOT NULL,
    APP_ENV_ID    INTEGER NOT NULL ,
    VERSION       VARCHAR2(32 CHAR) NOT NULL ,
    EXIT_CODE     INTEGER NULL ,
    OUT           CLOB NULL ,
    ERR           CLOB NULL ,
    STACK_TRACE   CLOB NULL ,
    JOB_START     DATE NOT NULL , -- Does not handle DST as local time (oh well - it's complicated to do so in JPA)
    JOB_END       DATE NULL , -- Does not handle DST
    CONSTRAINT REMOTE_COMMAND_RESULT_PK PRIMARY KEY (DEPLOY_JOB_ID) ,
    CONSTRAINT ENV_FK1 FOREIGN KEY (APP_ENV_ID) REFERENCES ADM_OWNER.APP_ENV (APP_ENV_ID) ON DELETE CASCADE
);