services:
  oracle:
    image: gvenzl/oracle-xe:21.3.0
    hostname: oracle
    ports:
      - "127.0.0.1:${ADM_ORACLE_PORT:-1521}:1521"
      - "127.0.0.1:${ADM_ORACLE_EM_PORT:-5500}:5500"
    environment:
      ORACLE_PASSWORD: testing
      TZ: 'America/New_York'
    volumes:
      - ./container/oracle/initdb.d:/container-entrypoint-initdb.d

  keycloak:
    image: jeffersonlab/keycloak:2.6.0
    hostname: keycloak
    ports:
      - "127.0.0.1:${ADM_KEYCLOAK_PORT:-8081}:8080"
      - "127.0.0.1:${ADM_KEYCLOAK_MANAGEMENT_PORT:-9991}:9990"
    environment:
      KC_FRONTEND_URL: 'http://localhost:${ADM_KEYCLOAK_PORT:-8081}/auth'
      KC_BACKEND_URL: 'http://keycloak:8080/auth'
      KC_HTTP_RELATIVE_PATH: '/auth'
      KC_BOOTSTRAP_ADMIN_USERNAME: 'admin'
      KC_BOOTSTRAP_ADMIN_PASSWORD: 'admin'
      KC_CLIENT_NAME: adm
      KC_RESOURCE: adm
      KC_REDIRECT_URIS: '["https://localhost:${ADM_HTTPS_PORT:-8443}/adm/*"]'
    volumes:
      - ./container/keycloak/initdb.d/03_customize.sh:/container-entrypoint-initdb.d/03_customize.sh


  sshd:
    build:
      context: .
      dockerfile: Dockerfile-sshd
    hostname: sshd
    ports:
      - "127.0.0.1:${ADM_SSHD_PORT:-1234}:22"
    environment:
      TEST_USER_AUTHORIZED_KEY: ${TEST_USER_AUTHORIZED_KEY}