FROM alpine:3.19

ARG CUSTOM_CRT_URL=http://pki.jlab.org/JLabCA.crt

RUN if [ -z "$CUSTOM_CRT_URL" ] ; then echo "No custom cert needed"; else \
              mkdir -p /usr/local/share/ca-certificates \
              && wget -O /usr/local/share/ca-certificates/customcert.crt $CUSTOM_CRT_URL \
              && cat /usr/local/share/ca-certificates/customcert.crt >> /etc/ssl/certs/ca-certificates.crt \
    ; fi \
    && apk update \
    && apk add openssh shadow tini bash \
    && useradd -m -s /bin/bash testuser \
    && echo "testuser:password" | chpasswd \
    && mkdir /home/testuser/.ssh \
    && chown testuser:testuser /home/testuser/.ssh \
    && chmod 0700 /home/testuser/.ssh \
    && ssh-keygen -A \
    && echo "LogLevel=DEBUG3" >> /etc/ssh/sshd_config

EXPOSE 22

COPY ./container/sshd/container-entrypoint.sh /

ENTRYPOINT ["/sbin/tini", "--", "/container-entrypoint.sh"]