name: Release

on:
  push:
    paths:
      - './VERSION'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Build
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
      - name: Build with Gradle
        run: ./gradlew build
      - name: Read version file
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: build/libs/adm.war
          tag_name: v${{ env.VERSION }}